import Slider from "react-slick";
import UsesTemplate1 from "../templates/UsesTemplate1";
import UsesTemplate2 from "../templates/UsesTemplate2";

function UsesOfSolarPanel() {
  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 4,
    // slidesToScroll: 4,
    arrows: false,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 1000,
    pauseOnHover: true,
    initialSlide: 0,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
          initialSlide: 2,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };
  return (
    <div className="slider-container h-[70vh]  pl-[40px] mb-11 ">
      <Slider {...settings}>
        <div>
          <UsesTemplate1
            Heading="Solar Panel"
            Purpose="A solar panel captures sunlight and converts it into electricity, providing a renewable, sustainable energy source for homes, businesses, and other applications. It's a core component of solar energy systems, helping reduce reliance on fossil fuels."
            Link=""
            image="https://mercurydirect.com.ng/wp-content/uploads/2017/11/260-Solar-System-1.jpg"
          />
        </div>
        <div>
          <UsesTemplate2
            Heading=" Solar Genarator"
            Purpose="A solar generator stores energy generated from solar panels in a battery, allowing for backup power supply during outages or when solar energy is unavailable. It provides an eco-friendly, portable, and reliable power source for both indoor and outdoor use."
            Link=""
            image="https://ae01.alicdn.com/kf/Ha1203db6f9de48b99430e0a862d4b4ffR.jpg?width=750&height=750&hash=1500"
          />
        </div>
        <div>
          <UsesTemplate1
            Heading="Inverter"
            Purpose="An inverter converts the direct current (DC) electricity generated by solar panels into alternating current (AC), which can be used by home appliances and fed into the power grid."
            Link=""
            image="https://energymall.ng/wp-content/uploads/2021/08/1kva-12v-solar-inverter-PWM.jpg"
          />
        </div>
        <div>
          <UsesTemplate2
            Heading="Solar Street Light"
            Purpose="is a self-contained outdoor lighting system powered by solar energy. It uses solar panels to capture sunlight during the day, storing the energy in a battery to power LED lights at night, offering an eco-friendly and cost-effective solution for street and outdoor lighting
"
            Link=""
            image="https://5.imimg.com/data5/NP/VH/XY/SELLER-3568152/solar-street-light-500x500-250x250.jpg"
          />
        </div>

        <div>
          <UsesTemplate1
            Heading="CCTV Solar Powered camera"
            Purpose="A solar-powered CCTV camera is a surveillance system that operates using solar energy. It utilizes solar panels to harness sunlight, converting it into electricity to power the camera, making it ideal for remote locations where traditional power sources are unavailable. These cameras often feature motion detection, night vision, and cloud storage options, providing reliable security while minimizing environmental impact.
"
            Link=""
            image="https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/76/7525102/1.jpg?2954"
          />
        </div>
        <div>
          <UsesTemplate2
            Heading="Batteries"
            Purpose="Batteries are devices that store electrical energy for later use."
            Link=""
            image="https://rspsupply.com/images/content/Solar%20batteries.jpg"
          />
        </div>
        <div>
          <UsesTemplate1
            Heading="Solar Fan"
            Purpose="
A solar fan is a device powered by solar energy, typically using solar panels to convert sunlight into electricity. These fans are designed to provide ventilation and cooling without relying on grid electricity, making them an eco-friendly solution. Solar fans are commonly used in homes, greenhouses, and outdoor spaces to improve air circulation, reduce heat buildup, and enhance comfort while promoting energy efficiency and sustainability."
            Link=""
            image="https://images-cdn.ubuy.co.in/63400e728c182f0e6430c402-cowin-solar-fan-system-solar-energy.jpg"
          />
        </div>
        <div>
          <UsesTemplate2
            Heading="Solar Touch"
            Purpose="These products can include solar-powered sensors, lights, or heating systems that are easy to operate and integrate seamlessly into various environments. "
            Link=""
            image="https://kara.com.ng/media/catalog/product/cache/acf1a829635e5a35e3be9ccd68062a20/i/m/img-20240103-wa0014_3.jpg"
          />
        </div>
        <div>
          <UsesTemplate1
            Heading="Solar Electric Meter"
            Purpose="A solar electric meter is a device that measures the amount of electricity generated by a solar energy system. It provides important information regarding energy production, helping users track the performance of their solar panels."
            Link=""
            image="https://solarnaturally.com.au/wp-content/uploads/2018/11/Depositphotos_11130530_s-2015.jpg"
          />
        </div>
        <div>
          <UsesTemplate2
            Heading="MTTP"
            Purpose="MTTP adjusts the operating point of the solar panels to ensure they operate at their maximum power output, regardless of changes in environmental conditions (such as temperature, sunlight intensity, and shading"
            Link=""
            image="https://www.xindun-power.com/uploadfile/upload/2021-05/19/MPPTWonder196V100A2.jpg"
          />
        </div>
      </Slider>
    </div>
  );
}

export default UsesOfSolarPanel;
